## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION_LABEL: ${{ github.sha }}
  ELASTIC_BEANSTALK_NAME: desafio-santander-usuario
  ELASTIC_BEANSTALK_ENV_NAME: desafio-santander-usuario-env
  DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Upload .jar
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/quarkus-app/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: sa-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload artifact to S3
        run: |
          aws s3 cp "quarkus-run.jar" s3://elasticbeanstalk-sa-east-1-${{ secrets.AWS_ACCOUNT_ID }}/artifact/usuario/app.jar

      - name: Criar aplicação
        run: |
          aws elasticbeanstalk create-application-version --application-name $ELASTIC_BEANSTALK_NAME --version-label $VERSION_LABEL --description $VERSION_LABEL --source-bundle S3Bucket="elasticbeanstalk-sa-east-1-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="artifact/usuario/app.jar"

      - name: Implantar aplicação
        run: |
          aws elasticbeanstalk update-environment --environment-name $ELASTIC_BEANSTALK_ENV_NAME --version-label $VERSION_LABEL
          aws elasticbeanstalk wait environment-updated --application-name $ELASTIC_BEANSTALK_NAME --environment-name $ELASTIC_BEANSTALK_ENV_NAME
